### PR TITLE
fix: check for min rating

### LINKED ISSUE #73: Bug: Viewing Product Page leads to a Whitelabel Error Page
After adding a product from the UI, clicking on the product shows a 500 error from the webserver.

### PR DESCRIPTION
**Pull request by Aashna-Verma**
Closes #73

### CODE REVIEW

**Review by AmileshN — APPROVED** [review]

**Review by AbhiramSureshkumar — APPROVED** [review]

File: src/main/java/org/slayscale/ProductController.java [hunk 1]
```diff
@@ -42,7 +42,7 @@ public ResponseEntity<Set<Review>> getProductReviews(
             reviewsSet = Set.of();
         }
 
-        int effectiveMin = minRating;
+        int effectiveMin = (minRating == null ? Review.MIN_RATING : minRating);
```
Comment (hubertdang) [inline src/main/java/org/slayscale/ProductController.java]: This shouldn't need to be here. We should be putting a `defaultValue` in the view controller's endpoint that delegates work to this one.

And in that case, we can also get rid of the `effectiveMin` variable since it won't be doing anything

**Review by hubertdang — CHANGES_REQUESTED** [review]
